---
apiVersion: ecs.aws.amazon.com/v1
kind: TaskDefinition
metadata:
  name: marvel-task
spec:
  family: marvel-task
  networkMode: awsvpc
  requiresCompatibilities:
    - FARGATE
  cpu: 256
  memory: 512
  executionRoleArn: arn:aws:iam::your-account-id:role/ecsTaskExecutionRole
  containerDefinitions:
    - name: marvel-container
      image: 688567283917.dkr.ecr.us-east-1.amazonaws.com/marvel:v1
      memory: 512
      cpu: 256
      essential: true
      portMappings:
        - containerPort: 80
          hostPort: 80
          protocol: tcp
